spring.application.name=expense_tracker

## mongo db setup
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=expense_tracker

logging.level.org.springframework.data.mongodb.core=DEBUG

# this will still work even with ide error message
jwt.secret=expense-tracker-application-for-cpsc-449-final-project
jwt.expiration=84000000